[package]
name = "halo2-verifier"
version = "1.0.0"
authors = ["zkmove contributors"]

[addresses]
halo2_verifier = "_"
[dev-addresses]
halo2_verifier = "0x1234"
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
