[package]
name = "halo2-common"
version = "1.0.0"
authors = ["zkmove contributors"]

[addresses]
halo2_common = "_"

[dev-addresses]
halo2_common = "0x123"

[dependencies.AptosFramework]
git = "https://github.com/zkmove/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
